[project]
name = "star-helix-cli"
version = "0.1.0"
description = ""
authors = [
    {name = "Paul Bailey", email = "paul@cognitivespace.com"},
]
dependencies = [
    "typer",
    "haikunator",
    "asynchronousfilereader",
]
requires-python = ">=3.7"
license = {text = "MIT"}

[project.urls]
homepage = ""

[tool]
[tool.pdm]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
